apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-devops-gke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gcp
  template:
    metadata:
      labels:
        app: gcp
    spec:
      containers:
      - name: gcp-devops-gke
        image: gcr.io/web-app-project-gcp/gcpdevops:latest
        ports:
        - containerPort: 11888
        env:
          - name: PORT
            value: "11888"
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "gcp-devops-gke-service"
  namespace: "web-app-prod"
  labels:
    app.kubernetes.io/managed-by: "gcp-cloud-build-deploy"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 11888
  selector:
    app: "gcp"
  type: "LoadBalancer"